repos:
  - repo: local
    hooks:
      - id: check-compilability
        name: "🐍 Checking compilability"
        entry: uv run python -m compileall
        language: system
        types: [ python ]
        pass_filenames: false
        always_run: true
      - id: pytest
        name: "🧪 Running tests"
        entry: uv run pytest
        language: system
        types: [ python ]
        pass_filenames: false
        always_run: true
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-ast
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.6.16
    hooks:
      # To ensure the lockfile is up-to-date:
      - id: uv-lock
      # To autoexport uv.lock to requirements.txt:
      - id: uv-export
#  - repo: https://github.com/astral-sh/ruff-pre-commit
#    rev: v0.11.6
#    hooks:
#      # Run the ruff linter.
#      - id: ruff
#        args: [ --fix ]