"""add args and error_message to log_bot_interaction

Revision ID: 3d330f671fdb
Revises: a5dce28a13f3
Create Date: 2026-04-23 02:02:48.875966

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3d330f671fdb'
down_revision: Union[str, None] = 'a5dce28a13f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log_bot_interaction', sa.Column('args', sa.TEXT(), nullable=True))
    op.add_column('log_bot_interaction', sa.Column('error_message', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('log_bot_interaction', 'error_message')
    op.drop_column('log_bot_interaction', 'args')
    # ### end Alembic commands ###
