"""migrate_shipsize_to_rolesize

Revision ID: 4766c5c1fedf
Revises: 3d330f671fdb
Create Date: 2026-04-26 22:12:48.223036

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4766c5c1fedf'
down_revision: Union[str, None] = '3d330f671fdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Since SQLAlchemy creates role_size on startup, we migrate the data using raw SQL 
    # instead of renaming the table to avoid 'table already exists' conflicts.
    op.execute(
        "INSERT INTO role_size (role_id, role_type, member_count, log_time) "
        "SELECT ship_role_id, 'SHIP', member_count, log_time FROM ship_size;"
    )

    op.drop_index(op.f('ix_ship_size_log_time'), table_name='ship_size')
    op.drop_table('ship_size')
    # ### end Alembic commands ###


def downgrade() -> None:
    op.create_table('ship_size',
                    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
                    sa.Column('ship_role_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
                    sa.Column('member_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
                    sa.Column('log_time', mysql.DATETIME(), nullable=False),
                    sa.PrimaryKeyConstraint('id', 'ship_role_id'),
                    mysql_collate='utf8mb4_general_ci',
                    mysql_default_charset='utf8mb4',
                    mysql_engine='InnoDB'
                    )
    op.create_index(op.f('ix_ship_size_log_time'), 'ship_size', ['log_time'], unique=False)

    op.execute(
        "INSERT INTO ship_size (ship_role_id, member_count, log_time) "
        "SELECT role_id, member_count, log_time FROM role_size WHERE role_type='SHIP';"
    )
