"""Add expanded health metrics

Revision ID: a5dce28a13f3
Revises: d68983d58bc8
Create Date: 2026-04-23 01:37:40.909739

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a5dce28a13f3'
down_revision: Union[str, None] = 'd68983d58bc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('health_snapshot', sa.Column('discord_latency_ms', sa.FLOAT(), nullable=True))
    op.add_column('health_snapshot', sa.Column('bot_cpu_usage_percent', sa.FLOAT(), nullable=True))
    op.add_column('health_snapshot', sa.Column('system_cpu_usage_percent', sa.FLOAT(), nullable=True))
    op.add_column('health_snapshot', sa.Column('system_total_memory_mb', sa.FLOAT(), nullable=True))
    op.add_column('health_snapshot', sa.Column('user_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('health_snapshot', 'user_count')
    op.drop_column('health_snapshot', 'system_total_memory_mb')
    op.drop_column('health_snapshot', 'system_cpu_usage_percent')
    op.drop_column('health_snapshot', 'bot_cpu_usage_percent')
    op.drop_column('health_snapshot', 'discord_latency_ms')
    # ### end Alembic commands ###
