"""add_rank_traceability

Revision ID: afc3160331ca
Revises: 4766c5c1fedf
Create Date: 2026-06-10 20:34:31.797879

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'afc3160331ca'
down_revision: Union[str, None] = '4766c5c1fedf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rank',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('identifier', sa.VARCHAR(length=16), nullable=False),
                    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
                    sa.Column('marine_name', sa.VARCHAR(length=64), nullable=True),
                    sa.Column('index', sa.Integer(), nullable=False),
                    sa.Column('role_id', sa.BIGINT(), nullable=False),
                    sa.Column('is_active', sa.BOOLEAN(), server_default='1', nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('role_id')
                    )
    op.create_table('log_rank_history',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('sailor_id', sa.BIGINT(), nullable=False),
                    sa.Column('rank_id', sa.Integer(), nullable=False),
                    sa.Column('log_time', sa.DATETIME(), nullable=False),
                    sa.Column('reason', sa.TEXT(), nullable=True),
                    sa.ForeignKeyConstraint(['rank_id'], ['rank.id'], ),
                    sa.ForeignKeyConstraint(['sailor_id'], ['sailor.discord_id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_log_rank_history_log_time'), 'log_rank_history', ['log_time'], unique=False)
    op.add_column('hosted', sa.Column('host_rank_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'hosted', 'rank', ['host_rank_id'], ['id'])
    op.add_column('sailor', sa.Column('current_rank_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sailor', 'rank', ['current_rank_id'], ['id'])
    op.add_column('voyages', sa.Column('participant_rank_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'voyages', 'rank', ['participant_rank_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'voyages', type_='foreignkey')
    op.drop_column('voyages', 'participant_rank_id')
    op.drop_constraint(None, 'sailor', type_='foreignkey')
    op.drop_column('sailor', 'current_rank_id')
    op.drop_constraint(None, 'hosted', type_='foreignkey')
    op.drop_column('hosted', 'host_rank_id')
    op.drop_index(op.f('ix_log_rank_history_log_time'), table_name='log_rank_history')
    op.drop_table('log_rank_history')
    op.drop_table('rank')
    # ### end Alembic commands ###
