"""add_monitoring_schema

Revision ID: d68983d58bc8
Revises: a8d9f3c4b217
Create Date: 2026-04-17 23:01:57.455904

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd68983d58bc8'
down_revision: Union[str, None] = 'a8d9f3c4b217'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_snapshot',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('timestamp', sa.DATETIME(), nullable=False),
                    sa.Column('pool_size', sa.Integer(), nullable=False),
                    sa.Column('checked_out', sa.Integer(), nullable=False),
                    sa.Column('overflow', sa.Integer(), nullable=False),
                    sa.Column('checked_in', sa.Integer(), nullable=False),
                    sa.Column('avg_cmd_latency', sa.FLOAT(), nullable=True),
                    sa.Column('max_cmd_latency', sa.FLOAT(), nullable=True),
                    sa.Column('memory_usage_mb', sa.FLOAT(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_health_snapshot_timestamp'), 'health_snapshot', ['timestamp'], unique=False)
    op.create_index(op.f('ix_log_ban_change_log_time'), 'log_ban_change', ['log_time'], unique=False)
    op.add_column('log_bot_interaction', sa.Column('interaction_id', sa.BIGINT(), nullable=True))
    op.add_column('log_bot_interaction', sa.Column('execution_time_ms', sa.FLOAT(), nullable=True))
    op.create_index(op.f('ix_log_bot_interaction_interaction_id'), 'log_bot_interaction', ['interaction_id'],
                    unique=False)
    op.create_index(op.f('ix_log_bot_interaction_log_time'), 'log_bot_interaction', ['log_time'], unique=False)
    op.create_index(op.f('ix_log_leave_change_log_time'), 'log_leave_change', ['log_time'], unique=False)
    op.create_index(op.f('ix_log_name_change_log_time'), 'log_name_change', ['log_time'], unique=False)
    op.create_index(op.f('ix_log_role_change_log_time'), 'log_role_change', ['log_time'], unique=False)
    op.create_index(op.f('ix_log_timeout_log_time'), 'log_timeout', ['log_time'], unique=False)
    op.create_index(op.f('ix_ship_size_log_time'), 'ship_size', ['log_time'], unique=False)
    op.create_index(op.f('ix_training_log_time'), 'training', ['log_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_log_time'), table_name='training')
    op.drop_index(op.f('ix_ship_size_log_time'), table_name='ship_size')
    op.drop_index(op.f('ix_log_timeout_log_time'), table_name='log_timeout')
    op.drop_index(op.f('ix_log_role_change_log_time'), table_name='log_role_change')
    op.drop_index(op.f('ix_log_name_change_log_time'), table_name='log_name_change')
    op.drop_index(op.f('ix_log_leave_change_log_time'), table_name='log_leave_change')
    op.drop_index(op.f('ix_log_bot_interaction_log_time'), table_name='log_bot_interaction')
    op.drop_index(op.f('ix_log_bot_interaction_interaction_id'), table_name='log_bot_interaction')
    op.drop_column('log_bot_interaction', 'execution_time_ms')
    op.drop_column('log_bot_interaction', 'interaction_id')
    op.drop_index(op.f('ix_log_ban_change_log_time'), table_name='log_ban_change')
    op.drop_index(op.f('ix_health_snapshot_timestamp'), table_name='health_snapshot')
    op.drop_table('health_snapshot')
    # ### end Alembic commands ###
