from src.config.main_server import (
    VOYAGE_PLANNING,
    VOYAGE_ANNOUNCEMENTS,
    UNOFFICIAL_VOYAGE_PLANNING,
)
from src.config.ranks_roles import (
    LF_PATROL_ROLE,
    LF_SKIRMISH_ROLE,
    LF_ADVENTURE_ROLE,
    LF_CONVOY_ROLE,
    LF_INSIDER_ROLE,
    LF_UNOFFICIAL_ROLE,
)

LFG_ROLES_CONFIG = {
    LF_PATROL_ROLE: "VOYAGE_LFG",
    LF_SKIRMISH_ROLE: "VOYAGE_LFG",
    LF_ADVENTURE_ROLE: "VOYAGE_LFG",
    LF_CONVOY_ROLE: "VOYAGE_LFG",
    LF_INSIDER_ROLE: "VOYAGE_LFG",
    LF_UNOFFICIAL_ROLE: "VOYAGE_LFG",
}

# Mapping of Channel ID -> Tracked Roles -> Ping Type
PING_TRACKING_CONFIG = {
    VOYAGE_PLANNING: LFG_ROLES_CONFIG,
    VOYAGE_ANNOUNCEMENTS: LFG_ROLES_CONFIG,
    UNOFFICIAL_VOYAGE_PLANNING: LFG_ROLES_CONFIG,
}
