from typing import Final

from src.config.main_server import BOT_TEST_COMMAND

HEAD_OF_SCHEDULING_ROLE_ID: Final[int] = 971780759566295110
XO_OF_SCHEDULING_ROLE_ID: Final[int] = 972947232720572456
HEAD_OF_MEDIA_ROLE_ID: Final[int] = 1077200853863243908
XO_OF_MEDIA_ROLE_ID: Final[int] = 1138105702313898024
SCHEDULING_REPRESENTATION_AWARDS_CHANNEL: Final[int] = BOT_TEST_COMMAND
MEDIA_REPRESENTATION_AWARDS_CHANNEL: Final[int] = BOT_TEST_COMMAND

SCHEDULING_REPRESENTATION_MANAGER_ROLE_IDS: Final[tuple[int, ...]] = (
    HEAD_OF_SCHEDULING_ROLE_ID,
    XO_OF_SCHEDULING_ROLE_ID,
)
MEDIA_REPRESENTATION_MANAGER_ROLE_IDS: Final[tuple[int, ...]] = (
    HEAD_OF_MEDIA_ROLE_ID,
    XO_OF_MEDIA_ROLE_ID,
)
ALL_REPRESENTATION_MANAGER_ROLE_IDS: Final[tuple[int, ...]] = (
    *SCHEDULING_REPRESENTATION_MANAGER_ROLE_IDS,
    *MEDIA_REPRESENTATION_MANAGER_ROLE_IDS,
)
