name: "🔍 Continuous Integration"

on:
  push:
    branches: [ "master", "main", "dev", "development" ]
  pull_request:
    branches: [ "master", "main", "dev", "development" ]

jobs:
  test:
    name: "🧪 Running Tests"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.13"
          - "3.14"
    steps:
      - name: "⌛ Checking out the code"
        uses: actions/checkout@v3
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: "📦 Installing dependencies"
        run: uv sync --locked --all-extras --dev
      - name: "🧪 Running tests"
        # For example, using `pytest`
        run: uv run pytest tests
#  format:
#    name: "🧹 Format Checking"
#    runs-on: ubuntu-latest
#    steps:
#      - name: "⌛ Checking out the code"
#        uses: actions/checkout@v3
#      - name: "🐍 Setting up Python"
#        uses: actions/setup-python@v4
#        with:
#          python-version: '3.14'
#      - name: "📦 Installing dependencies"
#        run: pip install black ruff
#      - name: "🧹 Running Black"
#        run: black --check src
#      - name: "🧹 Running Ruff"
#        run: ruff src